# Generated by Django 4.2.19 on 2025-02-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_username', models.CharField(max_length=255, unique=True)),
                ('github_token', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
