# Generated by Django 4.2.19 on 2025-02-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0002_githubcredentials_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='commithistory',
            name='is_pushed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commithistory',
            name='messages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
