# Generated by Django 4.2.19 on 2025-02-14 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commits', '0003_commithistory_is_pushed_commithistory_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='commithistory',
            name='new_repo',
            field=models.BooleanField(default=False),
        ),
    ]
